<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchoolsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('schools')->delete();
        
        \DB::table('schools')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'UNIVERSITY OF ABRA',
                'shortcut' => 'UA',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:20:26',
                'updated_at' => '2024-01-26 14:20:26',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ABUYOG COMMUNITY COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:31:26',
                'updated_at' => '2024-01-26 14:31:26',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ACES POLYTECHNIC COLLEGE',
                'shortcut' => 'APC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:36:17',
                'updated_at' => '2024-01-26 14:36:17',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'ACES TAGUM COLLEGE, INC.',
                'shortcut' => 'ATC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:40:18',
                'updated_at' => '2024-01-26 14:40:18',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'ACLC COLLEGE',
                'shortcut' => 'AC',
                'combiner' => 'OF',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:45:24',
                'updated_at' => '2024-01-26 14:45:24',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ACSI COLLEGE ILOILO',
                'shortcut' => 'ACI',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:58:06',
                'updated_at' => '2024-01-26 14:58:06',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'ACTS COMPUTER COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:01:04',
                'updated_at' => '2024-01-26 15:01:04',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'ADAMSON UNIVERSITY',
                'shortcut' => 'ADU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:03:10',
                'updated_at' => '2024-01-26 15:03:10',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'ADIONG MEMORIAL POLYTECHNIC STATE COLLEGE',
                'shortcut' => 'AMSC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:05:14',
                'updated_at' => '2024-01-26 15:05:14',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'ADVENTIST MEDICAL CENTER COLLEGE',
                'shortcut' => 'AMCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:07:45',
                'updated_at' => '2024-01-26 15:07:45',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ADVENTIST UNIVERSITY OF THE PHILIPPINES',
                'shortcut' => 'AUP',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:09:31',
                'updated_at' => '2024-01-26 15:09:31',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'AEMILIANUM COLLEGE, INC.',
                'shortcut' => 'ACI',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:13:26',
                'updated_at' => '2024-01-26 15:13:26',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'AGO MEDICAL AND EDUCATIONAL CENTER - BICOL CHRISTIAN COLLEGE OF MEDICINE',
                'shortcut' => 'AMEC-BCCM',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:18:56',
                'updated_at' => '2024-01-26 15:18:56',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'AGUSAN DEL SUR STATE COLLEGE OF AGRICULTURE AND TECHNOLOGY',
                'shortcut' => 'ASSCAT',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:01:35',
                'updated_at' => '2024-01-26 16:01:35',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'AKLAN CATHOLIC COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:03:20',
                'updated_at' => '2024-01-26 16:03:20',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'AKLAN POLYTECHNIC COLLEGE',
                'shortcut' => 'APC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:05:51',
                'updated_at' => '2024-01-26 16:05:51',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'AKLAN STATE UNIVERSITY',
                'shortcut' => 'ASU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:07:37',
                'updated_at' => '2024-01-26 16:07:37',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'ALDERGATE COLLEGE, INC.',
                'shortcut' => 'AC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:11:41',
                'updated_at' => '2024-01-26 16:11:41',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'AMA COMPUTER COLLEGE',
                'shortcut' => 'AMA',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:15:52',
                'updated_at' => '2024-01-26 16:15:52',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'AMA COMPUTER LEARNING CENTER',
                'shortcut' => 'ACLC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:10:49',
                'updated_at' => '2024-01-26 22:10:49',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'AMA UNIVERSITY',
                'shortcut' => 'AMA',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:14:16',
                'updated_at' => '2024-01-26 22:14:16',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'AMANDO COPE COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:21:20',
                'updated_at' => '2024-01-26 22:21:20',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'ANDRES BONIFACIO COLLEGE',
                'shortcut' => 'ABC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:24:15',
                'updated_at' => '2024-01-26 22:24:15',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'ANGELES UNIVERSITY FOUNDATION',
                'shortcut' => 'AUF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:25:34',
                'updated_at' => '2024-01-26 22:25:34',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'APAYAO STATE COLLEGE',
                'shortcut' => 'ASC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:29:33',
                'updated_at' => '2024-01-26 22:29:33',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ARELLANO UNIVERSITY',
                'shortcut' => 'AU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:34:55',
                'updated_at' => '2024-01-26 22:34:55',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'ARRIESGADO COLLEGE FOUNDATION, INC.',
                'shortcut' => 'ACF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:38:45',
                'updated_at' => '2024-01-26 22:38:45',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'ASIA PACIFIC COLLEGE',
                'shortcut' => 'APC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:40:36',
                'updated_at' => '2024-01-26 22:40:36',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'ASIA PACIFIC COLLEGE OF ADVANCE STUDIES',
                'shortcut' => 'APC-AS',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:41:33',
                'updated_at' => '2024-01-26 22:41:33',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'ASIA TECHNOLOGICAL SCHOOL OF SCIENCE AND ARTS',
                'shortcut' => 'ASIATECH',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:44:25',
                'updated_at' => '2024-01-26 22:44:25',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'ASIAN COLLEGE',
                'shortcut' => 'AC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:57:29',
                'updated_at' => '2024-01-26 22:57:29',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'ASIAN COLLEGE OF TECHNOLOGY - INTERNATIONAL EDUCATIONAL FOUNDATION',
                'shortcut' => 'ACT-IEF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:00:30',
                'updated_at' => '2024-01-26 23:00:30',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'ASIAN COLLEGE FOUNDATION',
                'shortcut' => 'ACF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:01:29',
                'updated_at' => '2024-01-26 23:01:29',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'ASSUMPTION COLLEGE',
                'shortcut' => 'AC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:04:46',
                'updated_at' => '2024-01-26 23:04:46',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'ASYNCHRONOUS SYSTEMS AND COMPUTER INFORMATION INSTITUTE',
                'shortcut' => 'ASCII',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:09:19',
                'updated_at' => '2024-01-26 23:09:19',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'ATENEO DE DAVAO UNIVERSITY',
                'shortcut' => 'ADDU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:11:59',
                'updated_at' => '2024-01-26 23:11:59',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'ATENEO DE MANILA UNIVERSITY',
                'shortcut' => 'ADMU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:12:16',
                'updated_at' => '2024-01-26 23:12:16',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'ATENEO DE NAGA UNIVERSITY',
                'shortcut' => 'ADNU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:12:35',
                'updated_at' => '2024-01-26 23:12:35',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'ATENEO DE ZAMBOANGA UNIVERSITY',
                'shortcut' => 'ADZU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:12:49',
                'updated_at' => '2024-01-26 23:12:49',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'AURORA STATE COLLEGE OF TECHNOLOGY',
                'shortcut' => 'ASCT',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:17:35',
                'updated_at' => '2024-01-26 23:17:35',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'B.E.S.T COLLEGE OF POLOMOLOK, INC.',
                'shortcut' => 'BCP',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:26:16',
                'updated_at' => '2024-01-26 23:26:16',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'BAAO COMMUNITY COLLEGE',
                'shortcut' => 'BCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:27:21',
                'updated_at' => '2024-01-26 23:27:21',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'BACOLOD CITY COLLEGE',
                'shortcut' => 'BCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:28:29',
                'updated_at' => '2024-01-26 23:28:29',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'BAGUIO CENTRAL UNIVERSITY',
                'shortcut' => 'BCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:29:47',
                'updated_at' => '2024-01-26 23:29:47',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'BAGUIO COLLEGE OF TECHNOLOGY',
                'shortcut' => 'BCT',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:31:21',
                'updated_at' => '2024-01-26 23:31:21',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'BALIAN COMMUNITY COLLEGE',
                'shortcut' => 'BCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:32:24',
                'updated_at' => '2024-01-26 23:32:24',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'BALIUAG UNIVERSITY',
                'shortcut' => 'BU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:33:42',
                'updated_at' => '2024-01-26 23:33:42',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'BALIWAG POLYTECHNIC COLLEGE',
                'shortcut' => 'BPC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:34:38',
                'updated_at' => '2024-01-26 23:34:38',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'BASILAN STATE COLLEGE',
                'shortcut' => 'BSC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:36:34',
                'updated_at' => '2024-01-26 23:36:34',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'BATAAN HEROES MEMORIAL COLLEGE',
                'shortcut' => 'BHMC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:41:27',
                'updated_at' => '2024-01-26 23:41:27',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'BATAAN PENINSULA STATE UNIVERSITY',
                'shortcut' => 'BPSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:45:00',
                'updated_at' => '2024-01-26 23:45:00',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'BATANES STATE COLLEGE',
                'shortcut' => 'BSC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:52:22',
                'updated_at' => '2024-01-26 23:52:22',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'BATANGAS STATE UNIVERSITY',
                'shortcut' => 'BSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:53:35',
                'updated_at' => '2024-01-26 23:53:35',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'BATUAN COLLEGES',
                'shortcut' => 'BC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 00:01:05',
                'updated_at' => '2024-01-27 00:01:05',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'BENGUET STATE UNIVERSITY',
                'shortcut' => 'BSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 00:02:49',
                'updated_at' => '2024-01-27 00:02:49',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'BESTLINK COLLEGE OF THE PHILIPPINES',
                'shortcut' => 'BCP',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 00:05:22',
                'updated_at' => '2024-01-27 00:05:22',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'BICOL COLLEGE',
                'shortcut' => 'BC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 00:06:35',
                'updated_at' => '2024-01-27 00:06:35',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'BICOL STATE COLLEGE OF APPLIED SCIENCES AND TECHNOLOGY',
                'shortcut' => 'BSCASAT',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 00:08:07',
                'updated_at' => '2024-01-27 00:08:07',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'BICOL UNIVERSITY',
                'shortcut' => 'BU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 00:11:56',
                'updated_at' => '2024-01-27 00:11:56',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'BILIRAN PROVINCE STATE UNIVERSITY',
                'shortcut' => 'BPSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:36:34',
                'updated_at' => '2024-01-27 11:36:34',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'BINANGONAN CATHOLIC COLLEGE',
                'shortcut' => 'BCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:38:50',
                'updated_at' => '2024-01-27 11:38:50',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'BLESSED MOTHER COLLEGE',
                'shortcut' => 'BMC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:40:09',
                'updated_at' => '2024-01-27 11:40:09',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'BLESSED TRINITY COLLEGE',
                'shortcut' => 'BTC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:41:54',
                'updated_at' => '2024-01-27 11:41:54',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'BOHOL ISLAND STATE UNIVERSITY',
                'shortcut' => 'BISU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:45:04',
                'updated_at' => '2024-01-27 11:45:04',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'BIT ITERNATIONAL COLLEGE',
                'shortcut' => 'BIC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:51:00',
                'updated_at' => '2024-01-27 11:51:00',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'BOHOL NORTHERN STAR COLLEGE',
                'shortcut' => 'BNSC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:55:20',
                'updated_at' => '2024-01-27 11:55:20',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'BOHOL WISDOM SCHOOL',
                'shortcut' => 'BWS',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:56:13',
                'updated_at' => '2024-01-27 11:56:13',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'BRENT HOSPITAL AND COLLEGES',
                'shortcut' => 'BHC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:57:31',
                'updated_at' => '2024-01-27 11:57:31',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'BROKENSHIRE COLLEGE',
                'shortcut' => 'BC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 11:59:58',
                'updated_at' => '2024-01-27 11:59:58',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'BUKIDNON STATE UNIVERSITY',
                'shortcut' => 'BSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:03:37',
                'updated_at' => '2024-01-27 12:03:37',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'BULACAN AGRICULTURAL STATE COLLEGE',
                'shortcut' => 'BASC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:09:15',
                'updated_at' => '2024-01-27 12:09:15',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'BULACAN STATE UNIVERSITY',
                'shortcut' => 'BSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:17:13',
                'updated_at' => '2024-01-27 12:17:13',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'BUTUAN DOCTORS COLLEGE',
                'shortcut' => 'BDC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:20:04',
                'updated_at' => '2024-01-27 12:20:04',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'CABALUM WESTERN COLLEGE',
                'shortcut' => 'CWC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:21:17',
                'updated_at' => '2024-01-27 12:21:17',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'CAGAYAN STATE UNIVERSITY',
                'shortcut' => 'CSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:23:13',
                'updated_at' => '2024-01-27 12:23:13',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'CALAMBA DOCTORS\' COLLEGE',
                'shortcut' => 'CDC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:28:44',
                'updated_at' => '2024-01-27 12:28:44',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'CALAYAN EDUCATIONAL FOUNDATION INC.',
                'shortcut' => 'CEF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:30:26',
                'updated_at' => '2024-01-27 12:30:26',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'CAMARINES NORTE COLLEGE OF ARTS AND BUSINESS INC.',
                'shortcut' => 'CNCAB',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:32:13',
                'updated_at' => '2024-01-27 12:32:13',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'CAMIGUIN POLYTECHNIC STATE COLLEGE',
                'shortcut' => 'CPSC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:33:52',
                'updated_at' => '2024-01-27 12:33:52',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'CANOSSA COLLEGE',
                'shortcut' => 'CC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:36:35',
                'updated_at' => '2024-01-27 12:36:35',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'CAPITOL UNIVERSITY',
                'shortcut' => 'CU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:38:41',
                'updated_at' => '2024-01-27 12:38:41',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'CAPIZ STATE UNIVERSITY',
                'shortcut' => 'CSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:42:35',
                'updated_at' => '2024-01-27 12:42:35',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'CARAGA STATE UNIVERSITY',
                'shortcut' => 'CSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:50:11',
                'updated_at' => '2024-01-27 12:50:11',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'CARCAR CITY COLLEGE',
                'shortcut' => 'CCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:52:42',
                'updated_at' => '2024-01-27 12:52:42',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'CARLOS HILADO MEMORIAL STATE UNIVERSITY',
                'shortcut' => 'CHMSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 12:54:46',
                'updated_at' => '2024-01-27 12:54:46',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'CARMELITE COLLEGE',
                'shortcut' => 'CC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:28:39',
                'updated_at' => '2024-01-27 15:28:39',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'CATANDUANES COLLEGE',
                'shortcut' => 'CC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:30:12',
                'updated_at' => '2024-01-27 15:30:12',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'CATANDUANES INSTITUTE OF TECHNOLOGY FOUNDATION',
                'shortcut' => 'CITF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:32:05',
                'updated_at' => '2024-01-27 15:32:05',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'CATANDUANES STATE UNIVERSITY',
                'shortcut' => 'CSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:33:50',
                'updated_at' => '2024-01-27 15:33:50',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'CATS AERO COLLEGE',
                'shortcut' => 'CAC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:36:14',
                'updated_at' => '2024-01-27 15:36:14',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'CAVITE STATE UNIVERSITY',
                'shortcut' => 'CSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:38:20',
                'updated_at' => '2024-01-27 15:38:20',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'CEBU DOCTORS UNIVERSITY',
                'shortcut' => 'CDU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:50:35',
                'updated_at' => '2024-01-27 15:50:35',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'CEBU EASTERN COLLEGE',
                'shortcut' => 'CEC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:52:05',
                'updated_at' => '2024-01-27 15:52:05',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'CEBU INSTITUTE OF TECHNOLOGY-UNIVERSITY',
                'shortcut' => 'CITU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:53:44',
                'updated_at' => '2024-01-27 15:53:44',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'CEBU NORMAL UNIVERSITY',
                'shortcut' => 'CNU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:54:51',
                'updated_at' => '2024-01-27 15:54:51',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'CEBU TECHNOLOGICAL UNIVERSITY',
                'shortcut' => 'CTU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 15:56:15',
                'updated_at' => '2024-01-27 15:56:15',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'CENTER FOR INDUSTRIAL TECHNOLOGY AND ENTERPRISE TECHNICAL INSTITUTE, INC.',
                'shortcut' => 'CITETI',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 16:04:41',
                'updated_at' => '2024-01-27 16:04:41',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'CENTRAL BICOL STATE UNIVERSITY OF AGRICULTURE',
                'shortcut' => 'CBSUA',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 16:06:20',
                'updated_at' => '2024-01-27 16:06:20',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'CENTRAL COLLEGES OF THE PHILIPPINES',
                'shortcut' => 'CCP',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 16:10:08',
                'updated_at' => '2024-01-27 16:10:08',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'CENTRAL LUZON DOCTORS\' HOSPITAL EDUCATIONAL INSTITUTION',
                'shortcut' => 'CLDHEI',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-27 16:12:02',
                'updated_at' => '2024-01-27 16:12:02',
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'CENTRAL LUZON STATE UNIVERSITY',
                'shortcut' => 'CLSU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:11:15',
                'updated_at' => '2024-02-02 09:11:15',
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'CENTRAL MINDANAO UNIVERSITY',
                'shortcut' => 'CMU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:13:32',
                'updated_at' => '2024-02-02 09:13:32',
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'CENTRAL PHILIPPINE ADVENTIST COLLEGE',
                'shortcut' => 'CPAC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:15:14',
                'updated_at' => '2024-02-02 09:15:14',
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'CENTRAL PHILIPPINE UNIVERSITY',
                'shortcut' => 'CPU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:16:54',
                'updated_at' => '2024-02-02 09:16:54',
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'CENTRAL PHILIPPINES STATE UNIVERSITY',
                'shortcut' => 'CPSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:19:13',
                'updated_at' => '2024-02-02 09:19:13',
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'CENTRO ESCOLAR UNIVERSITY',
                'shortcut' => 'CEU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:25:26',
                'updated_at' => '2024-02-02 09:25:26',
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'CHINESE GENERAL HOSPITAL COLLEGES',
                'shortcut' => 'CGHC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:28:13',
                'updated_at' => '2024-02-02 09:28:13',
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'CHRIST THE KING COLLEGE DE MARANDING, INC.',
                'shortcut' => 'CKCDM',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:29:34',
                'updated_at' => '2024-02-02 09:29:34',
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'CHRIST THE KING COLLEGE',
                'shortcut' => 'CKC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:35:43',
                'updated_at' => '2024-02-02 09:35:43',
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'CHRISTIAN COLLEGE OF TANAUAN',
                'shortcut' => 'CCT',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:40:14',
                'updated_at' => '2024-02-02 09:40:14',
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'CHRISTIAN COLLEGE SOUTHEAST ASIA',
                'shortcut' => 'CCSA',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 09:41:01',
                'updated_at' => '2024-02-02 09:41:01',
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'CHRISTIAN POLYTECHNIC INSTITUTE OF CATANDUANES, INC.',
                'shortcut' => 'CPIC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 10:13:39',
                'updated_at' => '2024-02-02 10:13:39',
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'CIIT PHILIPPINES',
                'shortcut' => 'CP',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 10:15:32',
                'updated_at' => '2024-02-02 10:15:32',
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'CITY COLLEGE OF ANGELES',
                'shortcut' => 'CCA',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:30:36',
                'updated_at' => '2024-02-02 11:30:36',
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'CITY COLLEGE OF CALAMBA',
                'shortcut' => 'CCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:32:36',
                'updated_at' => '2024-02-02 11:32:36',
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'CITY COLLEGE OF CALAPAN',
                'shortcut' => 'CCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:34:15',
                'updated_at' => '2024-02-02 11:34:15',
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'CITY COLLEGE OF TAGAYTAY',
                'shortcut' => 'CCT',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:35:19',
                'updated_at' => '2024-02-02 11:35:19',
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'CITY UNIVERSITY OF PASAY',
                'shortcut' => 'CUP',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:36:15',
                'updated_at' => '2024-02-02 11:36:15',
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'COLAND SYSTEMS TECHNOLOGY COLLEGE INC.',
                'shortcut' => 'CSTC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:37:42',
                'updated_at' => '2024-02-02 11:37:42',
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'UNIVERSIDAD DE DAGUPAN',
                'shortcut' => 'UDD',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:41:20',
                'updated_at' => '2024-02-02 11:41:20',
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'DIPOLOG CITY INSTITUTE OF TECHNOLOGY',
                'shortcut' => 'DCIT',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:45:18',
                'updated_at' => '2024-02-02 11:45:18',
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'DMC COLLEGE FOUNDATION, INC.',
                'shortcut' => 'DMC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:47:39',
                'updated_at' => '2024-02-02 11:47:39',
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'DR. AURELIO MENDOZA MEMORIAL COLLEGES',
                'shortcut' => 'DRAMMC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:48:46',
                'updated_at' => '2024-02-02 11:48:46',
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'JH CERILLES STATE COLLEGE',
                'shortcut' => 'JHCHC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:50:05',
                'updated_at' => '2024-02-02 11:50:05',
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'JOSE RIZAL MEMORIAL STATE UNIVERSITY',
                'shortcut' => 'JRMSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 11:54:59',
                'updated_at' => '2024-02-02 11:54:59',
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'MARIAN COLLEGE',
                'shortcut' => 'MC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 13:55:31',
                'updated_at' => '2024-02-02 13:55:31',
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'MEDINA COLLEGE',
                'shortcut' => 'MC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:04:27',
                'updated_at' => '2024-02-02 14:04:27',
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'MINDANAO STATE UNIVERSITY',
                'shortcut' => 'MSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:12:32',
                'updated_at' => '2024-02-02 14:12:32',
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'PAGADIAN CAPITOL COLLEGE, INC.',
                'shortcut' => 'PCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:21:30',
                'updated_at' => '2024-02-02 14:21:30',
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'PHILIPPINE ADVENT COLLEGE',
                'shortcut' => 'PAC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:22:34',
                'updated_at' => '2024-02-02 14:22:34',
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'SAINT COLUMBAN COLLEGE',
                'shortcut' => 'SCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:24:24',
                'updated_at' => '2024-02-02 14:24:24',
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'SAINT JOSEPH COLLEGE OF SINDANGAN INCORPORATED',
                'shortcut' => 'SJCSI',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:26:34',
                'updated_at' => '2024-02-02 14:26:34',
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'SAINT VINCENT\'S COLLEGE',
                'shortcut' => 'SVC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:28:32',
                'updated_at' => '2024-02-02 14:28:32',
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'SIBUGAY TECHNICAL INSTITUTE, INC.',
                'shortcut' => 'STII',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:29:58',
                'updated_at' => '2024-02-02 14:29:58',
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'SOUTHERN MINDANAO COLLEGES',
                'shortcut' => 'SMC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:31:18',
                'updated_at' => '2024-02-02 14:31:18',
            ),
            135 => 
            array (
                'id' => 136,
                'name' => 'UNIVERSIDAD DE ZAMBOANGA',
                'shortcut' => 'UZ',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:34:01',
                'updated_at' => '2024-02-02 14:34:01',
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'WESTERN MINDANAO STATE UNIVERSITY',
                'shortcut' => 'WMSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:43:13',
                'updated_at' => '2024-02-02 14:43:13',
            ),
            137 => 
            array (
                'id' => 138,
                'name' => 'YLLANA BAY VIEW COLLEGE',
                'shortcut' => 'YBVC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:46:25',
                'updated_at' => '2024-02-02 14:46:25',
            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'ZAMBOANGA DEL SUR PAGADIAN GOVERNMENT COLLEGE',
                'shortcut' => 'ZDSPGC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:47:32',
                'updated_at' => '2024-02-02 14:47:32',
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'ZAMBOANGA DEL SUR PROVINCIAL GOVERNMENT COLLEGE',
                'shortcut' => 'ZDSPGC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:49:28',
                'updated_at' => '2024-02-02 14:49:28',
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'ZAMBOANGA PENINSULA POLYTECHNIC STATE UNIVERSITY',
                'shortcut' => 'ZPPSU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:50:48',
                'updated_at' => '2024-02-02 14:50:48',
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'ZAMBOANGA STATE COLLEGE OF MARINE SCIENCE AND TECHNOLOGY',
                'shortcut' => 'ZSCMST',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-02-02 14:54:09',
                'updated_at' => '2024-02-02 14:54:09',
            ),
        ));
        
        
    }
}